services:
  gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  worker:
    build: ./services/worker
    shm_size: "3gb"
    depends_on:
      - postgres
      - redis
      - mlflow
    env_file:
      - .env

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --allowed-hosts "mlflow:5000,localhost:5000,localhost:5001"
      
volumes:
  postgres_data:
  mlflow_data: